# swapnavue/docker-compose.yml
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    environment:
      TOKENIZERS_PARALLELISM: "false"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      DATA_DIR: ${DATA_DIR:-/app/data}
      SENTENCE_TRANSFORMERS_HOME: /app/models/sentence_transformers_cache
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./cache:/app/cache
      - ./data:/app/data
      - ./.env:/app/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  db_data:
  sentence_transformers_cache: